CREATE TABLE Fruit
(
    fruit_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    warehousingDate date,
    price int,
    sold_yn boolean
);

CREATE TABLE Fruitsold
(
    fruitSold_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fruit_id bigint, 
    foreign key(fruit_id) references fruit (fruit_id)
);

